const GET_ALL = 'GET_ALL'
const GET_ALL_TEAMS = 'GET_ALL_TEAMS'
const UPDATE_SUGGESTED = 'UPDATE_SUGGESTED'
const GET_BY_NAME = 'GET_BY_NAME'
const UPDATE_TEAMS = 'UPDATE_TEAMS'
const UPDATE_ORIGIN = 'UPDATE_ORIGIN'
const UPDATE_ORDER = 'UPDATE_ORDER'

export {
    GET_ALL, 
    GET_ALL_TEAMS, 
    GET_BY_NAME, 
    UPDATE_SUGGESTED,
    UPDATE_TEAMS,
    UPDATE_ORIGIN,
    UPDATE_ORDER
};